-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 11, 2020 at 03:54 PM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `games`
--

-- --------------------------------------------------------

--
-- Table structure for table `games`
--

CREATE TABLE `games` (
  `ID` int(4) NOT NULL,
  `Name` varchar(255) NOT NULL,
  `Price` float NOT NULL,
  `Rating` int(1) NOT NULL,
  `isGotW` tinyint(1) NOT NULL,
  `Genre` varchar(255) NOT NULL,
  `short_desc` varchar(255) NOT NULL,
  `review` longtext NOT NULL,
  `link` varchar(2083) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `games`
--

INSERT INTO `games` (`ID`, `Name`, `Price`, `Rating`, `isGotW`, `Genre`, `short_desc`, `review`, `link`) VALUES
(1, 'Minecraft', 17.99, 5, 1, 'Sandbox', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sollicitudin nisi lorem, a euismod ligula volutpat nec. Vestibulum id tellus ante. Proin vel volutpat ligula. Vestibulum ante sapien, gravida eu diam eu, luctus pulvinar urna.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet arcu quis enim maximus imperdiet. Mauris accumsan sit amet velit id ultrices. Integer sed leo sodales, finibus quam ornare, viverra ante. Vestibulum justo quam, tempor sit amet dignissim vel, sagittis vel elit. Vestibulum feugiat consectetur risus at fringilla. Duis mattis volutpat dui quis laoreet. Donec eget lectus eget erat feugiat posuere. Aliquam erat volutpat. Nunc eleifend eleifend tellus non tempor. Nullam eu risus ipsum. Suspendisse potenti. Sed sollicitudin pellentesque nisl, nec ultrices elit varius ultricies. Integer eu nibh a ligula feugiat porta.  Nunc sit amet ipsum eros. Aenean pellentesque, nunc ac commodo molestie, ligula quam faucibus sapien, sed dapibus magna sem ut ipsum. Suspendisse aliquam magna eget diam posuere lacinia. Donec augue elit, iaculis bibendum lobortis a, ornare at augue. Vivamus vitae molestie eros. Suspendisse molestie fringilla augue, at auctor nisi sagittis quis. Curabitur molestie at purus non eleifend. Mauris mauris ex, pretium nec egestas luctus, dictum in arcu. Donec ante ex, suscipit at odio nec, facilisis elementum nisi. Vivamus iaculis pellentesque fringilla.  Nunc placerat, metus in mollis pharetra, diam metus iaculis neque, quis dictum sem quam quis nunc. Suspendisse volutpat nisi eget nisl volutpat, et posuere augue tristique. Aliquam commodo dui nec ultrices facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris congue ex id erat euismod, in pellentesque est feugiat. Cras quis felis nec erat accumsan eleifend. Suspendisse vitae nulla nec nisi consequat malesuada vel et orci. Donec feugiat elit ut tristique convallis. Praesent hendrerit arcu ut erat varius iaculis.', 'https://www.minecraft.net/en-us/'),
(3, 'Counter Strike: Global Offensive', 0, 4, 0, 'FPS', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sollicitudin nisi lorem, a euismod ligula volutpat nec. Vestibulum id tellus ante. Proin vel volutpat ligula. Vestibulum ante sapien, gravida eu diam eu, luctus pulvinar urna.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet arcu quis enim maximus imperdiet. Mauris accumsan sit amet velit id ultrices. Integer sed leo sodales, finibus quam ornare, viverra ante. Vestibulum justo quam, tempor sit amet dignissim vel, sagittis vel elit. Vestibulum feugiat consectetur risus at fringilla. Duis mattis volutpat dui quis laoreet. Donec eget lectus eget erat feugiat posuere. Aliquam erat volutpat. Nunc eleifend eleifend tellus non tempor. Nullam eu risus ipsum. Suspendisse potenti. Sed sollicitudin pellentesque nisl, nec ultrices elit varius ultricies. Integer eu nibh a ligula feugiat porta.\r\n\r\nNunc sit amet ipsum eros. Aenean pellentesque, nunc ac commodo molestie, ligula quam faucibus sapien, sed dapibus magna sem ut ipsum. Suspendisse aliquam magna eget diam posuere lacinia. Donec augue elit, iaculis bibendum lobortis a, ornare at augue. Vivamus vitae molestie eros. Suspendisse molestie fringilla augue, at auctor nisi sagittis quis. Curabitur molestie at purus non eleifend. Mauris mauris ex, pretium nec egestas luctus, dictum in arcu. Donec ante ex, suscipit at odio nec, facilisis elementum nisi. Vivamus iaculis pellentesque fringilla.\r\n\r\nNunc placerat, metus in mollis pharetra, diam metus iaculis neque, quis dictum sem quam quis nunc. Suspendisse volutpat nisi eget nisl volutpat, et posuere augue tristique. Aliquam commodo dui nec ultrices facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris congue ex id erat euismod, in pellentesque est feugiat. Cras quis felis nec erat accumsan eleifend. Suspendisse vitae nulla nec nisi consequat malesuada vel et orci. Donec feugiat elit ut tristique convallis. Praesent hendrerit arcu ut erat varius iaculis.', 'https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/'),
(4, 'Cities: Skylines', 22.99, 5, 0, 'Sandbox', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sollicitudin nisi lorem, a euismod ligula volutpat nec. Vestibulum id tellus ante. Proin vel volutpat ligula. Vestibulum ante sapien, gravida eu diam eu, luctus pulvinar urna.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet arcu quis enim maximus imperdiet. Mauris accumsan sit amet velit id ultrices. Integer sed leo sodales, finibus quam ornare, viverra ante. Vestibulum justo quam, tempor sit amet dignissim vel, sagittis vel elit. Vestibulum feugiat consectetur risus at fringilla. Duis mattis volutpat dui quis laoreet. Donec eget lectus eget erat feugiat posuere. Aliquam erat volutpat. Nunc eleifend eleifend tellus non tempor. Nullam eu risus ipsum. Suspendisse potenti. Sed sollicitudin pellentesque nisl, nec ultrices elit varius ultricies. Integer eu nibh a ligula feugiat porta.\r\n\r\nNunc sit amet ipsum eros. Aenean pellentesque, nunc ac commodo molestie, ligula quam faucibus sapien, sed dapibus magna sem ut ipsum. Suspendisse aliquam magna eget diam posuere lacinia. Donec augue elit, iaculis bibendum lobortis a, ornare at augue. Vivamus vitae molestie eros. Suspendisse molestie fringilla augue, at auctor nisi sagittis quis. Curabitur molestie at purus non eleifend. Mauris mauris ex, pretium nec egestas luctus, dictum in arcu. Donec ante ex, suscipit at odio nec, facilisis elementum nisi. Vivamus iaculis pellentesque fringilla.\r\n\r\nNunc placerat, metus in mollis pharetra, diam metus iaculis neque, quis dictum sem quam quis nunc. Suspendisse volutpat nisi eget nisl volutpat, et posuere augue tristique. Aliquam commodo dui nec ultrices facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris congue ex id erat euismod, in pellentesque est feugiat. Cras quis felis nec erat accumsan eleifend. Suspendisse vitae nulla nec nisi consequat malesuada vel et orci. Donec feugiat elit ut tristique convallis. Praesent hendrerit arcu ut erat varius iaculis.', 'https://store.steampowered.com/app/255710/Cities_Skylines/'),
(5, 'Assetto Corsa', 15.49, 5, 0, 'Virtual Racing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sollicitudin nisi lorem, a euismod ligula volutpat nec. Vestibulum id tellus ante. Proin vel volutpat ligula. Vestibulum ante sapien, gravida eu diam eu, luctus pulvinar urna.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet arcu quis enim maximus imperdiet. Mauris accumsan sit amet velit id ultrices. Integer sed leo sodales, finibus quam ornare, viverra ante. Vestibulum justo quam, tempor sit amet dignissim vel, sagittis vel elit. Vestibulum feugiat consectetur risus at fringilla. Duis mattis volutpat dui quis laoreet. Donec eget lectus eget erat feugiat posuere. Aliquam erat volutpat. Nunc eleifend eleifend tellus non tempor. Nullam eu risus ipsum. Suspendisse potenti. Sed sollicitudin pellentesque nisl, nec ultrices elit varius ultricies. Integer eu nibh a ligula feugiat porta.\r\n\r\nNunc sit amet ipsum eros. Aenean pellentesque, nunc ac commodo molestie, ligula quam faucibus sapien, sed dapibus magna sem ut ipsum. Suspendisse aliquam magna eget diam posuere lacinia. Donec augue elit, iaculis bibendum lobortis a, ornare at augue. Vivamus vitae molestie eros. Suspendisse molestie fringilla augue, at auctor nisi sagittis quis. Curabitur molestie at purus non eleifend. Mauris mauris ex, pretium nec egestas luctus, dictum in arcu. Donec ante ex, suscipit at odio nec, facilisis elementum nisi. Vivamus iaculis pellentesque fringilla.\r\n\r\nNunc placerat, metus in mollis pharetra, diam metus iaculis neque, quis dictum sem quam quis nunc. Suspendisse volutpat nisi eget nisl volutpat, et posuere augue tristique. Aliquam commodo dui nec ultrices facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris congue ex id erat euismod, in pellentesque est feugiat. Cras quis felis nec erat accumsan eleifend. Suspendisse vitae nulla nec nisi consequat malesuada vel et orci. Donec feugiat elit ut tristique convallis. Praesent hendrerit arcu ut erat varius iaculis.', 'https://store.steampowered.com/app/244210/Assetto_Corsa/'),
(6, 'Sid Meier\'s Civilization® V', 19.99, 5, 0, 'Strategy', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sollicitudin nisi lorem, a euismod ligula volutpat nec. Vestibulum id tellus ante. Proin vel volutpat ligula. Vestibulum ante sapien, gravida eu diam eu, luctus pulvinar urna.\r\n', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet arcu quis enim maximus imperdiet. Mauris accumsan sit amet velit id ultrices. Integer sed leo sodales, finibus quam ornare, viverra ante. Vestibulum justo quam, tempor sit amet dignissim vel, sagittis vel elit. Vestibulum feugiat consectetur risus at fringilla. Duis mattis volutpat dui quis laoreet. Donec eget lectus eget erat feugiat posuere. Aliquam erat volutpat. Nunc eleifend eleifend tellus non tempor. Nullam eu risus ipsum. Suspendisse potenti. Sed sollicitudin pellentesque nisl, nec ultrices elit varius ultricies. Integer eu nibh a ligula feugiat porta.\r\n\r\nNunc sit amet ipsum eros. Aenean pellentesque, nunc ac commodo molestie, ligula quam faucibus sapien, sed dapibus magna sem ut ipsum. Suspendisse aliquam magna eget diam posuere lacinia. Donec augue elit, iaculis bibendum lobortis a, ornare at augue. Vivamus vitae molestie eros. Suspendisse molestie fringilla augue, at auctor nisi sagittis quis. Curabitur molestie at purus non eleifend. Mauris mauris ex, pretium nec egestas luctus, dictum in arcu. Donec ante ex, suscipit at odio nec, facilisis elementum nisi. Vivamus iaculis pellentesque fringilla.\r\n\r\nNunc placerat, metus in mollis pharetra, diam metus iaculis neque, quis dictum sem quam quis nunc. Suspendisse volutpat nisi eget nisl volutpat, et posuere augue tristique. Aliquam commodo dui nec ultrices facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris congue ex id erat euismod, in pellentesque est feugiat. Cras quis felis nec erat accumsan eleifend. Suspendisse vitae nulla nec nisi consequat malesuada vel et orci. Donec feugiat elit ut tristique convallis. Praesent hendrerit arcu ut erat varius iaculis.', 'https://store.steampowered.com/app/8930/Sid_Meiers_Civilization_V/'),
(7, 'Americas Army: Proving Grounds', 0, 3, 0, 'Action', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sollicitudin nisi lorem, a euismod ligula volutpat nec. Vestibulum id tellus ante. Proin vel volutpat ligula. Vestibulum ante sapien, gravida eu diam eu, luctus pulvinar urna.\r\n', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet arcu quis enim maximus imperdiet. Mauris accumsan sit amet velit id ultrices. Integer sed leo sodales, finibus quam ornare, viverra ante. Vestibulum justo quam, tempor sit amet dignissim vel, sagittis vel elit. Vestibulum feugiat consectetur risus at fringilla. Duis mattis volutpat dui quis laoreet. Donec eget lectus eget erat feugiat posuere. Aliquam erat volutpat. Nunc eleifend eleifend tellus non tempor. Nullam eu risus ipsum. Suspendisse potenti. Sed sollicitudin pellentesque nisl, nec ultrices elit varius ultricies. Integer eu nibh a ligula feugiat porta.\r\n\r\nNunc sit amet ipsum eros. Aenean pellentesque, nunc ac commodo molestie, ligula quam faucibus sapien, sed dapibus magna sem ut ipsum. Suspendisse aliquam magna eget diam posuere lacinia. Donec augue elit, iaculis bibendum lobortis a, ornare at augue. Vivamus vitae molestie eros. Suspendisse molestie fringilla augue, at auctor nisi sagittis quis. Curabitur molestie at purus non eleifend. Mauris mauris ex, pretium nec egestas luctus, dictum in arcu. Donec ante ex, suscipit at odio nec, facilisis elementum nisi. Vivamus iaculis pellentesque fringilla.\r\n\r\nNunc placerat, metus in mollis pharetra, diam metus iaculis neque, quis dictum sem quam quis nunc. Suspendisse volutpat nisi eget nisl volutpat, et posuere augue tristique. Aliquam commodo dui nec ultrices facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris congue ex id erat euismod, in pellentesque est feugiat. Cras quis felis nec erat accumsan eleifend. Suspendisse vitae nulla nec nisi consequat malesuada vel et orci. Donec feugiat elit ut tristique convallis. Praesent hendrerit arcu ut erat varius iaculis.', 'https://store.steampowered.com/app/203290/Americas_Army_Proving_Grounds/'),
(8, 'Half-Life: Alyx\r\n', 46.49, 4, 0, 'Action', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sollicitudin nisi lorem, a euismod ligula volutpat nec. Vestibulum id tellus ante. Proin vel volutpat ligula. Vestibulum ante sapien, gravida eu diam eu, luctus pulvinar urna.\r\n', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet arcu quis enim maximus imperdiet. Mauris accumsan sit amet velit id ultrices. Integer sed leo sodales, finibus quam ornare, viverra ante. Vestibulum justo quam, tempor sit amet dignissim vel, sagittis vel elit. Vestibulum feugiat consectetur risus at fringilla. Duis mattis volutpat dui quis laoreet. Donec eget lectus eget erat feugiat posuere. Aliquam erat volutpat. Nunc eleifend eleifend tellus non tempor. Nullam eu risus ipsum. Suspendisse potenti. Sed sollicitudin pellentesque nisl, nec ultrices elit varius ultricies. Integer eu nibh a ligula feugiat porta.\r\n\r\nNunc sit amet ipsum eros. Aenean pellentesque, nunc ac commodo molestie, ligula quam faucibus sapien, sed dapibus magna sem ut ipsum. Suspendisse aliquam magna eget diam posuere lacinia. Donec augue elit, iaculis bibendum lobortis a, ornare at augue. Vivamus vitae molestie eros. Suspendisse molestie fringilla augue, at auctor nisi sagittis quis. Curabitur molestie at purus non eleifend. Mauris mauris ex, pretium nec egestas luctus, dictum in arcu. Donec ante ex, suscipit at odio nec, facilisis elementum nisi. Vivamus iaculis pellentesque fringilla.\r\n\r\nNunc placerat, metus in mollis pharetra, diam metus iaculis neque, quis dictum sem quam quis nunc. Suspendisse volutpat nisi eget nisl volutpat, et posuere augue tristique. Aliquam commodo dui nec ultrices facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris congue ex id erat euismod, in pellentesque est feugiat. Cras quis felis nec erat accumsan eleifend. Suspendisse vitae nulla nec nisi consequat malesuada vel et orci. Donec feugiat elit ut tristique convallis. Praesent hendrerit arcu ut erat varius iaculis.', 'https://store.steampowered.com/app/546560/HalfLife_Alyx/'),
(9, 'Farming Simulator 19', 21.99, 5, 0, 'Simulation', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sollicitudin nisi lorem, a euismod ligula volutpat nec. Vestibulum id tellus ante. Proin vel volutpat ligula. Vestibulum ante sapien, gravida eu diam eu, luctus pulvinar urna.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet arcu quis enim maximus imperdiet. Mauris accumsan sit amet velit id ultrices. Integer sed leo sodales, finibus quam ornare, viverra ante. Vestibulum justo quam, tempor sit amet dignissim vel, sagittis vel elit. Vestibulum feugiat consectetur risus at fringilla. Duis mattis volutpat dui quis laoreet. Donec eget lectus eget erat feugiat posuere. Aliquam erat volutpat. Nunc eleifend eleifend tellus non tempor. Nullam eu risus ipsum. Suspendisse potenti. Sed sollicitudin pellentesque nisl, nec ultrices elit varius ultricies. Integer eu nibh a ligula feugiat porta.  Nunc sit amet ipsum eros. Aenean pellentesque, nunc ac commodo molestie, ligula quam faucibus sapien, sed dapibus magna sem ut ipsum. Suspendisse aliquam magna eget diam posuere lacinia. Donec augue elit, iaculis bibendum lobortis a, ornare at augue. Vivamus vitae molestie eros. Suspendisse molestie fringilla augue, at auctor nisi sagittis quis. Curabitur molestie at purus non eleifend. Mauris mauris ex, pretium nec egestas luctus, dictum in arcu. Donec ante ex, suscipit at odio nec, facilisis elementum nisi. Vivamus iaculis pellentesque fringilla.  Nunc placerat, metus in mollis pharetra, diam metus iaculis neque, quis dictum sem quam quis nunc. Suspendisse volutpat nisi eget nisl volutpat, et posuere augue tristique. Aliquam commodo dui nec ultrices facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris congue ex id erat euismod, in pellentesque est feugiat. Cras quis felis nec erat accumsan eleifend. Suspendisse vitae nulla nec nisi consequat malesuada vel et orci. Donec feugiat elit ut tristique convallis. Praesent hendrerit arcu ut erat varius iaculis.', 'https://store.steampowered.com/app/787860/Farming_Simulator_19/'),
(10, 'Grand Theft Auto V', 24.99, 5, 0, 'Action', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sollicitudin nisi lorem, a euismod ligula volutpat nec. Vestibulum id tellus ante. Proin vel volutpat ligula. Vestibulum ante sapien, gravida eu diam eu, luctus pulvinar urna.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet arcu quis enim maximus imperdiet. Mauris accumsan sit amet velit id ultrices. Integer sed leo sodales, finibus quam ornare, viverra ante. Vestibulum justo quam, tempor sit amet dignissim vel, sagittis vel elit. Vestibulum feugiat consectetur risus at fringilla. Duis mattis volutpat dui quis laoreet. Donec eget lectus eget erat feugiat posuere. Aliquam erat volutpat. Nunc eleifend eleifend tellus non tempor. Nullam eu risus ipsum. Suspendisse potenti. Sed sollicitudin pellentesque nisl, nec ultrices elit varius ultricies. Integer eu nibh a ligula feugiat porta.  Nunc sit amet ipsum eros. Aenean pellentesque, nunc ac commodo molestie, ligula quam faucibus sapien, sed dapibus magna sem ut ipsum. Suspendisse aliquam magna eget diam posuere lacinia. Donec augue elit, iaculis bibendum lobortis a, ornare at augue. Vivamus vitae molestie eros. Suspendisse molestie fringilla augue, at auctor nisi sagittis quis. Curabitur molestie at purus non eleifend. Mauris mauris ex, pretium nec egestas luctus, dictum in arcu. Donec ante ex, suscipit at odio nec, facilisis elementum nisi. Vivamus iaculis pellentesque fringilla.  Nunc placerat, metus in mollis pharetra, diam metus iaculis neque, quis dictum sem quam quis nunc. Suspendisse volutpat nisi eget nisl volutpat, et posuere augue tristique. Aliquam commodo dui nec ultrices facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris congue ex id erat euismod, in pellentesque est feugiat. Cras quis felis nec erat accumsan eleifend. Suspendisse vitae nulla nec nisi consequat malesuada vel et orci. Donec feugiat elit ut tristique convallis. Praesent hendrerit arcu ut erat varius iaculis.', 'https://store.steampowered.com/app/271590/Grand_Theft_Auto_V/');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `games`
--
ALTER TABLE `games`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `games`
--
ALTER TABLE `games`
  MODIFY `ID` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
